#!/bin/bash

# Requirements :
# + Make the pre-commit file executable, e.g. chmod +x pre-commit
# + Symbol-link to the file in .git/hooks, e.g. ln -s $(pwd)/pre-commit $(pwd)/.git/hooks/

format_file() {
  file="${1}"
  if [ -f $file ]; then
    ${2} ${1}
    git add ${1}
  fi
}

case "${1}" in
  --about )
    echo "Runs clang-format and yapf3 on source files"
    ;;
  * )
    clang_cmd="clang-format -i -style=file"
    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
      format_file "${file}" "${clang_cmd}"
    done
    ;;
esac
